blank_issues_enabled: false
contact_links:
  - name: 访问 xxtsoft 官网
    url: https://xxtsoft.top
    about: 看看我的最新力作（
  - name: 加入 QQ 群
    url: https://qm.qq.com/q/q47G4JiePK
    about: 在 QQ 群和开发者以及其它用户交流讨论。（群号：821944413）
