name: 功能请求
description: 提出一项新的功能。
title: （将此栏【替换】为你的标题）
labels: ["新功能", "待查看", "优先级：无"]
type: 特性
body:
  - type: markdown
    attributes:
      value: |
        让我看看你有什么想法，请先在上面选一个标题吧~
        这个 Issues 模板是从 ![ClassIsland](https://github.com/ClassIsland/ClassIsland) 仓库里抄过来的。
        > [!important]
        > 重要：如果要提出 **多项功能**，请为每一个功能开一个单独的 issue。
        > 我暂时无适配 Linux 和适配 ClassIsland 1.x 的打算，因此我们尽量聊 Windows 的事；开始之前，也可以检查一下自己是否更新到最新版本，也许有些功能我已经加了。
        > 由于开发者时间精力有限，加上已经积压了大量的功能请求，提交的功能请求可能需要比较久的时间才能实现，但无论如何，我都很重视、很感谢每个人提出的 issue。
  - type: textarea
    id: back
    attributes:
      label: 背景与动机
      description: 这个功能有多好玩？为什么你很想要呢？
    validations:
      required: false
  - type: textarea
    id: requested-feature
    attributes:
      label: 想要实现或优化的功能
      description: 详细地描述一下你想要的功能，描述的越具体，采纳的可能性越高。
    validations:
      required: true
  - type: textarea
    id: expected-effect
    attributes:
      label: 期望效果
      description: 如果你真能实现这个功能，那我会看到……
    validations:
      required: true